# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    cors_allow_credentials: true
    cors_allow_origin: ['*']
    cors_allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'HEAD', 'OPTIONS']
    cors_allow_headers: ['DNT','X-Custom-Header','Keep-Alive','User-Agent','X-Requested-With','If-Modified-Since','Cache-Control','Content-Type','Content-Range','Range', 'Authorization']
    cors_max_age: 1728000

services:
    # default configuration for services in *this* file
    _instanceof:
        App\PickAlgorithm\PickAlgorithmInterface:
            tags: ['app.picking_algorithm']

    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $pickingMethods: !tagged_locator { tag: 'app.picking_algorithm', default_index_method: 'getName' }

    App\:
        resource: '%kernel.project_dir%/src/'
        exclude:
            - '%kernel.project_dir%/src/Model/'
            - '%kernel.project_dir%/src/Kernel.php'
            - '%kernel.project_dir%/src/functions.php'

    React\EventLoop\Factory: ~

    React\EventLoop\LoopInterface:
        factory: ['@React\EventLoop\Factory', 'create']

    Sikei\React\Http\Middleware\CorsMiddleware:
        arguments:
            $settings:
                allow_credentials: '%env(default:cors_allow_credentials:CORS_ALLOW_CREDENTIALS)%'
                allow_origin: '%env(default:cors_allow_origin:CORS_ALLOW_ORIGIN)%'
                allow_methods: '%env(default:cors_allow_methods:CORS_ALLOW_METHODS)%'
                allow_headers: '%env(default:cors_allow_headers:CORS_ALLOW_HEADERS)%'
                max_age: '%env(default:cors_max_age:CORS_MAX_AGE)%'

    App\PickAlgorithm\PickAlgorithmInterface: '@App\PickAlgorithm\RoundRobin'
